version: "3"
services:
  db:
    build:
      context: ./
      dockerfile: ./deploy/docker/Dockerfile.db
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
  dev:
    build:
      context: ./
      dockerfile: ./deploy/docker/Dockerfile.backend
    command:
      - /bin/sh
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    stdin_open: true
    tty: true
    depends_on:
      - db
volumes:
  pg_data: