version: "3"
services:
  db:
    build:
      context: ./
      dockerfile: ./deploy/docker/Dockerfile.db
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
  dev:
    build:
      context: ./
      dockerfile: ./deploy/docker/Dockerfile.backend
    command:
      - /bin/sh
      - -c
      - |
        python manage.py migrate
        gunicorn wsgi:application
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    stdin_open: true
    tty: true
    depends_on:
      - db
  frontend:
    build:
      context: ./
      dockerfile: ./deploy/docker/Dockerfile.frontend
    command:
      - /bin/sh
      - -c
      - |
        yarn start
    volumes:
      - ./frontend:/app
      - /app/node_modules/
      - /app/.next
    ports:
      - 3000:3000
    env_file:
      - .env
    stdin_open: true
    tty: true
volumes:
  pg_data: